### ISSUE TITLE
http://keplerproject.org | Website Down

### ISSUE THREAD

**Issue by arsenx** [keplerproject/kepler#1]
Hi guys i've been checking up for 2-3 days now and the website seems to be down any updates?

**Comment by mpeterv** [comment]
It's been down for a long time, and I don't think it's supposed to be working. @hishamhm  perhaps the link should be removed from https://github.com/keplerproject?

**Comment by hishamhm** [comment]
@mpeterv Removed.

@arsenx That website no longer exists. The Kepler Project "disbanded" into several projects that were either deprecated or are now maintained independently.

**Comment by arsenx** [comment]
I see, so those smaller projects are now using github's pages?

The reason why I ask is because I used to check out some examples on the luasql section of the keplerproject website and now they're nowhere to be found.

But thank you for clarifying

**Comment by hishamhm** [comment]
Yes: http://keplerproject.github.io/luasql

**Comment by arsenx** [comment]
Fantastic, it would be nice if someone could update the URL on the luasql page
